[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/public" = "dist/"

[[command]]
name = "serve"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["-w", "/public"]