[package]
name = "rilwag2612/onlinegames190"
version = "0.5.11"

[dependencies]
"wasmer/static-web-server" = "^1"

[fs]
"/public" = "dist"
"/settings" = "settings"

[[command]]
name = "script"
module = "wasmer/static-web-server:webserver"
runner = "https://webc.org/runner/wasi"

[command.annotations.wasi]
main-args = ["-w", "/settings/config.toml"]
